import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Golden Bloom Studs',
    price: 45.00,
    description: 'Delicate floral studs crafted from 18k gold plating, perfect for everyday elegance.',
    images: ['https://placehold.co/600x600', 'https://placehold.co/600x600'],
    category: 'stud',
    material: 'gold',
    color: 'gold',
    isNew: true,
  },
  {
    id: '2',
    name: 'Silver Celestial Hoops',
    price: 65.00,
    description: 'Sterling silver hoops featuring subtle star and moon engravings.',
    images: ['https://placehold.co/600x600', 'https://placehold.co/600x600'],
    category: 'hoop',
    material: 'silver',
    color: 'silver',
    isNew: false,
  },
  {
    id: '3',
    name: 'Emerald Drop Dangles',
    price: 89.99,
    description: 'Elegant dangles with a pear-cut created emerald, suspended from a gold-plated hook.',
    images: ['https://placehold.co/600x600', 'https://placehold.co/600x600'],
    category: 'dangle',
    material: 'gold',
    color: 'green',
    isNew: false,
  },
  {
    id: '4',
    name: 'Beaded Sunburst Earrings',
    price: 39.50,
    description: 'Hand-woven beaded earrings in a vibrant sunburst pattern.',
    images: ['https://placehold.co/600x600', 'https://placehold.co/600x600'],
    category: 'dangle',
    material: 'beads',
    color: 'pink',
    isNew: true,
  },
  {
    id: '5',
    name: 'Minimalist Gold Bar Studs',
    price: 35.00,
    description: 'Sleek and simple, these gold bar studs are a modern classic.',
    images: ['https://placehold.co/600x600', 'https://placehold.co/600x600'],
    category: 'stud',
    material: 'gold',
    color: 'gold',
    isNew: false,
  },
  {
    id: '6',
    name: 'Oceanic Wave Hoops',
    price: 75.00,
    description: 'Chunky silver hoops with a unique wave-like texture.',
    images: ['https://placehold.co/600x600', 'https://placehold.co/600x600'],
    category: 'hoop',
    material: 'silver',
    color: 'silver',
    isNew: false,
  },
  {
    id: '7',
    name: 'Rose Quartz Teardrops',
    price: 95.00,
    description: 'Gentle rose quartz stones in a teardrop shape, set in rose gold.',
    images: ['https://placehold.co/600x600', 'https://placehold.co/600x600'],
    category: 'dangle',
    material: 'gold',
    color: 'pink',
    isNew: false,
  },
  {
    id: '8',
    name: 'Midnight Blue Beaded Hoops',
    price: 55.00,
    description: 'Small hoops wrapped in tiny, shimmering midnight blue beads.',
    images: ['https://placehold.co/600x600', 'https://placehold.co/600x600'],
    category: 'hoop',
    material: 'beads',
    color: 'blue',
    isNew: true,
  },
];
